version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"                      # Expose PostgreSQL on port 5432

  web:
    build:
      context: .
      dockerfile: Dockerfile             # Specify the Dockerfile for the Go app
    restart: always
    environment:
      - DATABASE_URL=postgres://youruser:yourpassword@db/yourdb?sslmode=disable
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
    ports:
      - "8081:8081"                      # Expose the web app on port 8080
    depends_on:
      - db

volumes:
  postgres_data:
